/**
 * 工程工质物性库（自建公开参考数据）
 * 覆盖范围参考过程工业常用选型场景（水/蒸汽、工业气、烃类、溶剂、酸碱、热油、浆料等）
 * 参考态：液体约 20°C、1 atm；气体约 20°C、1 atm（除非注明）
 * 正式交付工况请用实测或状态方程复核；本库用于选型初算
 */

export type FluidPhase = 'liquid' | 'gas' | 'steam'

export type FluidCategory =
  | 'water_steam'
  | 'air_industrial_gas'
  | 'natural_gas_hydrocarbon_gas'
  | 'hydrocarbon_liquid'
  | 'fuel_oil'
  | 'alcohol_solvent'
  | 'acid_alkali'
  | 'refrigerant'
  | 'thermal_oil'
  | 'slurry_viscous'
  | 'cryogenic'
  | 'other'

export const CATEGORY_LABEL: Record<FluidCategory, string> = {
  water_steam: '水 / 蒸汽',
  air_industrial_gas: '空气与工业气体',
  natural_gas_hydrocarbon_gas: '天然气与烃类气',
  hydrocarbon_liquid: '液态烃 / 芳烃',
  fuel_oil: '燃料油 / 原油',
  alcohol_solvent: '醇类与溶剂',
  acid_alkali: '酸 / 碱 / 溶液',
  refrigerant: '制冷剂',
  thermal_oil: '导热油',
  slurry_viscous: '浆料 / 高粘',
  cryogenic: '低温介质',
  other: '其他',
}

export interface FluidProps {
  id: string
  name: string
  nameEn: string
  phase: FluidPhase
  category: FluidCategory
  /** kg/m³ @ 参考态 */
  density: number
  /** Pa·s */
  viscosity: number
  /** 等熵指数 κ */
  kappa?: number
  /** 分子量 g/mol */
  molarMass?: number
  /** 蒸汽压 Pa（液体，气蚀估算） */
  vaporPressure?: number
  /** 临界压力 Pa */
  pc?: number
  /** CAS（可选） */
  cas?: string
  /** 参考说明 */
  note?: string
  tags?: string[]
}

function L(
  partial: Omit<FluidProps, 'phase'> & { phase?: FluidPhase },
): FluidProps {
  return { phase: 'liquid', ...partial }
}

function G(
  partial: Omit<FluidProps, 'phase'> & { phase?: FluidPhase },
): FluidProps {
  return { phase: 'gas', ...partial }
}

function S(
  partial: Omit<FluidProps, 'phase'> & { phase?: FluidPhase },
): FluidProps {
  return { phase: 'steam', ...partial }
}

export const FLUIDS: FluidProps[] = [
  // —— 水 / 蒸汽 ——
  L({
    id: 'water_20c',
    name: '水 (20°C)',
    nameEn: 'Water 20°C',
    category: 'water_steam',
    density: 998.2,
    viscosity: 1.002e-3,
    vaporPressure: 2339,
    pc: 22.064e6,
    molarMass: 18.015,
    kappa: 1.33,
    cas: '7732-18-5',
    tags: ['IAPWS', '常用'],
  }),
  L({
    id: 'water_40c',
    name: '水 (40°C)',
    nameEn: 'Water 40°C',
    category: 'water_steam',
    density: 992.2,
    viscosity: 6.53e-4,
    vaporPressure: 7381,
    pc: 22.064e6,
    molarMass: 18.015,
  }),
  L({
    id: 'water_60c',
    name: '水 (60°C)',
    nameEn: 'Water 60°C',
    category: 'water_steam',
    density: 983.2,
    viscosity: 4.67e-4,
    vaporPressure: 19940,
    pc: 22.064e6,
    molarMass: 18.015,
  }),
  L({
    id: 'water_80c',
    name: '水 (80°C)',
    nameEn: 'Water 80°C',
    category: 'water_steam',
    density: 971.8,
    viscosity: 3.55e-4,
    vaporPressure: 47390,
    pc: 22.064e6,
    molarMass: 18.015,
  }),
  L({
    id: 'water_100c',
    name: '水 (100°C 饱和液)',
    nameEn: 'Water 100°C sat. liquid',
    category: 'water_steam',
    density: 958.4,
    viscosity: 2.82e-4,
    vaporPressure: 101325,
    pc: 22.064e6,
    molarMass: 18.015,
  }),
  L({
    id: 'sea_water',
    name: '海水 (3.5% 盐, 20°C)',
    nameEn: 'Seawater 3.5% 20°C',
    category: 'water_steam',
    density: 1025,
    viscosity: 1.08e-3,
    vaporPressure: 2300,
    note: '近似值，盐度影响粘度与密度',
  }),
  L({
    id: 'heavy_water',
    name: '重水 D₂O',
    nameEn: 'Heavy water',
    category: 'water_steam',
    density: 1105,
    viscosity: 1.25e-3,
    vaporPressure: 2000,
    molarMass: 20.028,
    cas: '7789-20-0',
  }),
  S({
    id: 'steam_sat_100c',
    name: '饱和蒸汽 (100°C, 1 atm)',
    nameEn: 'Sat. steam 100°C',
    category: 'water_steam',
    density: 0.598,
    viscosity: 1.22e-5,
    kappa: 1.33,
    molarMass: 18.015,
    tags: ['IAPWS-IF97'],
  }),
  S({
    id: 'steam_sat_150c',
    name: '饱和蒸汽 (150°C)',
    nameEn: 'Sat. steam 150°C',
    category: 'water_steam',
    density: 2.547,
    viscosity: 1.4e-5,
    kappa: 1.32,
    molarMass: 18.015,
  }),
  S({
    id: 'steam_sat_180c',
    name: '饱和蒸汽 (180°C)',
    nameEn: 'Sat. steam 180°C',
    category: 'water_steam',
    density: 5.157,
    viscosity: 1.5e-5,
    kappa: 1.31,
    molarMass: 18.015,
  }),
  S({
    id: 'steam_sh_200c_10bara',
    name: '过热蒸汽 (200°C, 10 bar(a))',
    nameEn: 'Superheated steam 200°C 10 bar(a)',
    category: 'water_steam',
    density: 4.61,
    viscosity: 1.6e-5,
    kappa: 1.3,
    molarMass: 18.015,
    note: '参考态密度，计算时仍可按 P/T 修正',
  }),
  S({
    id: 'steam_sh_300c_20bara',
    name: '过热蒸汽 (300°C, 20 bar(a))',
    nameEn: 'Superheated steam 300°C 20 bar(a)',
    category: 'water_steam',
    density: 7.71,
    viscosity: 2.0e-5,
    kappa: 1.29,
    molarMass: 18.015,
  }),

  // —— 空气与工业气体 ——
  G({
    id: 'air',
    name: '空气',
    nameEn: 'Air',
    category: 'air_industrial_gas',
    density: 1.204,
    viscosity: 1.825e-5,
    kappa: 1.4,
    molarMass: 28.97,
    tags: ['常用'],
  }),
  G({
    id: 'nitrogen',
    name: '氮气 N₂',
    nameEn: 'Nitrogen',
    category: 'air_industrial_gas',
    density: 1.165,
    viscosity: 1.76e-5,
    kappa: 1.4,
    molarMass: 28.013,
    cas: '7727-37-9',
  }),
  G({
    id: 'oxygen',
    name: '氧气 O₂',
    nameEn: 'Oxygen',
    category: 'air_industrial_gas',
    density: 1.331,
    viscosity: 2.03e-5,
    kappa: 1.4,
    molarMass: 31.999,
    cas: '7782-44-7',
  }),
  G({
    id: 'hydrogen',
    name: '氢气 H₂',
    nameEn: 'Hydrogen',
    category: 'air_industrial_gas',
    density: 0.0838,
    viscosity: 8.8e-6,
    kappa: 1.41,
    molarMass: 2.016,
    cas: '1333-74-0',
  }),
  G({
    id: 'helium',
    name: '氦气 He',
    nameEn: 'Helium',
    category: 'air_industrial_gas',
    density: 0.166,
    viscosity: 1.96e-5,
    kappa: 1.67,
    molarMass: 4.003,
    cas: '7440-59-7',
  }),
  G({
    id: 'argon',
    name: '氩气 Ar',
    nameEn: 'Argon',
    category: 'air_industrial_gas',
    density: 1.661,
    viscosity: 2.23e-5,
    kappa: 1.67,
    molarMass: 39.948,
    cas: '7440-37-1',
  }),
  G({
    id: 'co2',
    name: '二氧化碳 CO₂',
    nameEn: 'Carbon dioxide',
    category: 'air_industrial_gas',
    density: 1.839,
    viscosity: 1.47e-5,
    kappa: 1.3,
    molarMass: 44.01,
    cas: '124-38-9',
  }),
  G({
    id: 'co',
    name: '一氧化碳 CO',
    nameEn: 'Carbon monoxide',
    category: 'air_industrial_gas',
    density: 1.165,
    viscosity: 1.74e-5,
    kappa: 1.4,
    molarMass: 28.01,
    cas: '630-08-0',
  }),
  G({
    id: 'ammonia_gas',
    name: '氨气 NH₃',
    nameEn: 'Ammonia (gas)',
    category: 'air_industrial_gas',
    density: 0.717,
    viscosity: 1.0e-5,
    kappa: 1.31,
    molarMass: 17.031,
    cas: '7664-41-7',
  }),
  G({
    id: 'chlorine',
    name: '氯气 Cl₂',
    nameEn: 'Chlorine',
    category: 'air_industrial_gas',
    density: 2.98,
    viscosity: 1.33e-5,
    kappa: 1.35,
    molarMass: 70.906,
    cas: '7782-50-5',
  }),
  G({
    id: 'hcl_gas',
    name: '氯化氢 HCl',
    nameEn: 'Hydrogen chloride',
    category: 'air_industrial_gas',
    density: 1.52,
    viscosity: 1.4e-5,
    kappa: 1.4,
    molarMass: 36.46,
    cas: '7647-01-0',
  }),
  G({
    id: 'h2s',
    name: '硫化氢 H₂S',
    nameEn: 'Hydrogen sulfide',
    category: 'air_industrial_gas',
    density: 1.42,
    viscosity: 1.2e-5,
    kappa: 1.32,
    molarMass: 34.08,
    cas: '7783-06-4',
  }),
  G({
    id: 'so2',
    name: '二氧化硫 SO₂',
    nameEn: 'Sulfur dioxide',
    category: 'air_industrial_gas',
    density: 2.7,
    viscosity: 1.25e-5,
    kappa: 1.29,
    molarMass: 64.07,
    cas: '7446-09-5',
  }),
  G({
    id: 'sf6',
    name: '六氟化硫 SF₆',
    nameEn: 'Sulfur hexafluoride',
    category: 'air_industrial_gas',
    density: 6.17,
    viscosity: 1.5e-5,
    kappa: 1.09,
    molarMass: 146.06,
    cas: '2551-62-4',
  }),
  G({
    id: 'n2o',
    name: '氧化亚氮 N₂O',
    nameEn: 'Nitrous oxide',
    category: 'air_industrial_gas',
    density: 1.84,
    viscosity: 1.45e-5,
    kappa: 1.3,
    molarMass: 44.013,
    cas: '10024-97-2',
  }),
  G({
    id: 'biogas',
    name: '沼气 (约 60% CH₄)',
    nameEn: 'Biogas ~60% CH4',
    category: 'air_industrial_gas',
    density: 1.1,
    viscosity: 1.2e-5,
    kappa: 1.3,
    molarMass: 25,
    note: '组成变化大，建议按实际组分修正',
    tags: ['PRESO常用工况'],
  }),
  G({
    id: 'coke_oven_gas',
    name: '焦炉煤气',
    nameEn: 'Coke oven gas',
    category: 'air_industrial_gas',
    density: 0.45,
    viscosity: 1.1e-5,
    kappa: 1.35,
    molarMass: 11,
    note: '富氢，组成因厂而异',
    tags: ['PRESO常用工况'],
  }),
  G({
    id: 'flue_gas',
    name: '烟气 (典型)',
    nameEn: 'Flue gas typical',
    category: 'air_industrial_gas',
    density: 1.3,
    viscosity: 1.8e-5,
    kappa: 1.35,
    molarMass: 30,
  }),

  // —— 天然气与烃类气 ——
  G({
    id: 'methane',
    name: '甲烷 CH₄',
    nameEn: 'Methane',
    category: 'natural_gas_hydrocarbon_gas',
    density: 0.668,
    viscosity: 1.1e-5,
    kappa: 1.31,
    molarMass: 16.043,
    cas: '74-82-8',
  }),
  G({
    id: 'natural_gas_lean',
    name: '天然气 (贫气)',
    nameEn: 'Natural gas lean',
    category: 'natural_gas_hydrocarbon_gas',
    density: 0.72,
    viscosity: 1.1e-5,
    kappa: 1.3,
    molarMass: 16.8,
    note: '近似 AGA8 贫气；正式计量请用 AGA8/GERG',
    tags: ['AGA8'],
  }),
  G({
    id: 'natural_gas_rich',
    name: '天然气 (富气)',
    nameEn: 'Natural gas rich',
    category: 'natural_gas_hydrocarbon_gas',
    density: 0.9,
    viscosity: 1.15e-5,
    kappa: 1.28,
    molarMass: 20.5,
    tags: ['AGA8'],
  }),
  G({
    id: 'ethane',
    name: '乙烷 C₂H₆',
    nameEn: 'Ethane',
    category: 'natural_gas_hydrocarbon_gas',
    density: 1.264,
    viscosity: 9.2e-6,
    kappa: 1.19,
    molarMass: 30.07,
    cas: '74-84-0',
  }),
  G({
    id: 'propane_gas',
    name: '丙烷 (气) C₃H₈',
    nameEn: 'Propane gas',
    category: 'natural_gas_hydrocarbon_gas',
    density: 1.88,
    viscosity: 8.0e-6,
    kappa: 1.13,
    molarMass: 44.1,
    cas: '74-98-6',
  }),
  G({
    id: 'n_butane_gas',
    name: '正丁烷 (气)',
    nameEn: 'n-Butane gas',
    category: 'natural_gas_hydrocarbon_gas',
    density: 2.48,
    viscosity: 7.4e-6,
    kappa: 1.09,
    molarMass: 58.12,
    cas: '106-97-8',
  }),
  G({
    id: 'isobutane_gas',
    name: '异丁烷 (气)',
    nameEn: 'Isobutane gas',
    category: 'natural_gas_hydrocarbon_gas',
    density: 2.51,
    viscosity: 7.5e-6,
    kappa: 1.1,
    molarMass: 58.12,
    cas: '75-28-5',
  }),
  G({
    id: 'ethylene',
    name: '乙烯 C₂H₄',
    nameEn: 'Ethylene',
    category: 'natural_gas_hydrocarbon_gas',
    density: 1.178,
    viscosity: 1.0e-5,
    kappa: 1.25,
    molarMass: 28.05,
    cas: '74-85-1',
  }),
  G({
    id: 'propylene',
    name: '丙烯 C₃H₆',
    nameEn: 'Propylene',
    category: 'natural_gas_hydrocarbon_gas',
    density: 1.81,
    viscosity: 8.4e-6,
    kappa: 1.15,
    molarMass: 42.08,
    cas: '115-07-1',
  }),
  G({
    id: 'lpg_vapor',
    name: 'LPG 蒸气 (典型)',
    nameEn: 'LPG vapor typical',
    category: 'natural_gas_hydrocarbon_gas',
    density: 2.0,
    viscosity: 7.8e-6,
    kappa: 1.12,
    molarMass: 50,
  }),

  // —— 液态烃 / 芳烃 ——
  L({
    id: 'propane_liquid',
    name: '液态丙烷 (-42°C 参考 / 加压常温近似)',
    nameEn: 'Liquid propane',
    category: 'hydrocarbon_liquid',
    density: 500,
    viscosity: 1.1e-4,
    vaporPressure: 8.4e5,
    molarMass: 44.1,
    note: '加压储罐工况密度约 490–530 kg/m³',
  }),
  L({
    id: 'n_pentane',
    name: '正戊烷',
    nameEn: 'n-Pentane',
    category: 'hydrocarbon_liquid',
    density: 626,
    viscosity: 2.3e-4,
    vaporPressure: 5.7e4,
    molarMass: 72.15,
    cas: '109-66-0',
  }),
  L({
    id: 'n_hexane',
    name: '正己烷',
    nameEn: 'n-Hexane',
    category: 'hydrocarbon_liquid',
    density: 659,
    viscosity: 3.1e-4,
    vaporPressure: 1.7e4,
    molarMass: 86.18,
    cas: '110-54-3',
  }),
  L({
    id: 'n_heptane',
    name: '正庚烷',
    nameEn: 'n-Heptane',
    category: 'hydrocarbon_liquid',
    density: 684,
    viscosity: 4.1e-4,
    vaporPressure: 5300,
    molarMass: 100.2,
    cas: '142-82-5',
  }),
  L({
    id: 'n_octane',
    name: '正辛烷',
    nameEn: 'n-Octane',
    category: 'hydrocarbon_liquid',
    density: 703,
    viscosity: 5.4e-4,
    vaporPressure: 1500,
    molarMass: 114.23,
    cas: '111-65-9',
  }),
  L({
    id: 'cyclohexane',
    name: '环己烷',
    nameEn: 'Cyclohexane',
    category: 'hydrocarbon_liquid',
    density: 779,
    viscosity: 9.8e-4,
    vaporPressure: 1.03e4,
    molarMass: 84.16,
    cas: '110-82-7',
  }),
  L({
    id: 'benzene',
    name: '苯',
    nameEn: 'Benzene',
    category: 'hydrocarbon_liquid',
    density: 879,
    viscosity: 6.5e-4,
    vaporPressure: 1.0e4,
    molarMass: 78.11,
    cas: '71-43-2',
  }),
  L({
    id: 'toluene',
    name: '甲苯',
    nameEn: 'Toluene',
    category: 'hydrocarbon_liquid',
    density: 867,
    viscosity: 5.9e-4,
    vaporPressure: 2900,
    molarMass: 92.14,
    cas: '108-88-3',
  }),
  L({
    id: 'xylene_mixed',
    name: '混二甲苯',
    nameEn: 'Mixed xylene',
    category: 'hydrocarbon_liquid',
    density: 870,
    viscosity: 7.5e-4,
    vaporPressure: 900,
    molarMass: 106.17,
  }),
  L({
    id: 'ethylbenzene',
    name: '乙苯',
    nameEn: 'Ethylbenzene',
    category: 'hydrocarbon_liquid',
    density: 867,
    viscosity: 6.8e-4,
    vaporPressure: 950,
    molarMass: 106.17,
    cas: '100-41-4',
  }),
  L({
    id: 'gasoline',
    name: '汽油 (典型)',
    nameEn: 'Gasoline typical',
    category: 'hydrocarbon_liquid',
    density: 740,
    viscosity: 5.5e-4,
    vaporPressure: 4.5e4,
    tags: ['PRESO常用工况'],
  }),
  L({
    id: 'diesel',
    name: '柴油 (典型)',
    nameEn: 'Diesel typical',
    category: 'hydrocarbon_liquid',
    density: 840,
    viscosity: 3.0e-3,
    vaporPressure: 300,
    tags: ['PRESO常用工况'],
  }),
  L({
    id: 'kerosene',
    name: '煤油',
    nameEn: 'Kerosene',
    category: 'hydrocarbon_liquid',
    density: 810,
    viscosity: 1.6e-3,
    vaporPressure: 500,
  }),
  L({
    id: 'jet_a',
    name: '航空煤油 Jet-A',
    nameEn: 'Jet-A',
    category: 'hydrocarbon_liquid',
    density: 800,
    viscosity: 1.5e-3,
    vaporPressure: 1000,
  }),
  L({
    id: 'naphtha',
    name: '石脑油',
    nameEn: 'Naphtha',
    category: 'hydrocarbon_liquid',
    density: 720,
    viscosity: 5.0e-4,
    vaporPressure: 3.5e4,
  }),

  // —— 燃料油 / 原油 ——
  L({
    id: 'light_crude',
    name: '轻质原油 (API 40)',
    nameEn: 'Light crude API40',
    category: 'fuel_oil',
    density: 825,
    viscosity: 0.005,
    vaporPressure: 2e4,
    tags: ['PRESO常用工况'],
  }),
  L({
    id: 'medium_crude',
    name: '中质原油 (API 30)',
    nameEn: 'Medium crude API30',
    category: 'fuel_oil',
    density: 876,
    viscosity: 0.02,
    vaporPressure: 1e4,
  }),
  L({
    id: 'heavy_crude',
    name: '重质原油 (API 20)',
    nameEn: 'Heavy crude API20',
    category: 'fuel_oil',
    density: 934,
    viscosity: 0.2,
    vaporPressure: 2000,
    tags: ['楔形计适用'],
  }),
  L({
    id: 'fuel_oil_light',
    name: '轻质燃料油',
    nameEn: 'Light fuel oil',
    category: 'fuel_oil',
    density: 870,
    viscosity: 0.01,
    vaporPressure: 100,
  }),
  L({
    id: 'fuel_oil_heavy',
    name: '重质燃料油 (HFO)',
    nameEn: 'Heavy fuel oil',
    category: 'fuel_oil',
    density: 960,
    viscosity: 0.5,
    vaporPressure: 50,
    note: '常需加热；粘度随温度剧变',
    tags: ['楔形计适用'],
  }),
  L({
    id: 'bitumen',
    name: '沥青 / 焦油 (参考高温)',
    nameEn: 'Bitumen / tar',
    category: 'fuel_oil',
    density: 1020,
    viscosity: 1.5,
    vaporPressure: 10,
    note: '极高粘，PRESO COIN 楔形典型工况',
    tags: ['PRESO COIN'],
  }),

  // —— 醇类与溶剂 ——
  L({
    id: 'methanol',
    name: '甲醇',
    nameEn: 'Methanol',
    category: 'alcohol_solvent',
    density: 792,
    viscosity: 5.9e-4,
    vaporPressure: 1.28e4,
    molarMass: 32.04,
    cas: '67-56-1',
  }),
  L({
    id: 'ethanol',
    name: '乙醇',
    nameEn: 'Ethanol',
    category: 'alcohol_solvent',
    density: 789,
    viscosity: 1.2e-3,
    vaporPressure: 5900,
    molarMass: 46.07,
    cas: '64-17-5',
  }),
  L({
    id: 'ipa',
    name: '异丙醇 IPA',
    nameEn: 'Isopropanol',
    category: 'alcohol_solvent',
    density: 785,
    viscosity: 2.4e-3,
    vaporPressure: 4400,
    molarMass: 60.1,
  }),
  L({
    id: 'acetone',
    name: '丙酮',
    nameEn: 'Acetone',
    category: 'alcohol_solvent',
    density: 790,
    viscosity: 3.2e-4,
    vaporPressure: 2.45e4,
    molarMass: 58.08,
    cas: '67-64-1',
  }),
  L({
    id: 'meoh_water_50',
    name: '甲醇水溶液 50%wt',
    nameEn: 'Methanol-water 50%wt',
    category: 'alcohol_solvent',
    density: 915,
    viscosity: 1.5e-3,
    vaporPressure: 8000,
  }),
  L({
    id: 'ethanol_water_50',
    name: '乙醇水溶液 50%wt',
    nameEn: 'Ethanol-water 50%wt',
    category: 'alcohol_solvent',
    density: 914,
    viscosity: 2.5e-3,
    vaporPressure: 5000,
  }),
  L({
    id: 'glycol',
    name: '乙二醇',
    nameEn: 'Ethylene glycol',
    category: 'alcohol_solvent',
    density: 1113,
    viscosity: 0.021,
    vaporPressure: 10,
    molarMass: 62.07,
  }),
  L({
    id: 'glycol_water_50',
    name: '乙二醇水溶液 50%wt',
    nameEn: 'EG-water 50%wt',
    category: 'alcohol_solvent',
    density: 1070,
    viscosity: 0.004,
    vaporPressure: 1500,
    tags: ['HVAC'],
  }),
  L({
    id: 'glycerol',
    name: '甘油',
    nameEn: 'Glycerol',
    category: 'alcohol_solvent',
    density: 1260,
    viscosity: 1.4,
    vaporPressure: 0.01,
    molarMass: 92.09,
  }),
  L({
    id: 'chloroform',
    name: '氯仿',
    nameEn: 'Chloroform',
    category: 'alcohol_solvent',
    density: 1489,
    viscosity: 5.7e-4,
    vaporPressure: 2.1e4,
    molarMass: 119.38,
  }),
  L({
    id: 'dichloromethane',
    name: '二氯甲烷',
    nameEn: 'Dichloromethane',
    category: 'alcohol_solvent',
    density: 1327,
    viscosity: 4.3e-4,
    vaporPressure: 4.7e4,
    molarMass: 84.93,
  }),
  L({
    id: 'thf',
    name: '四氢呋喃 THF',
    nameEn: 'Tetrahydrofuran',
    category: 'alcohol_solvent',
    density: 889,
    viscosity: 4.8e-4,
    vaporPressure: 1.7e4,
    molarMass: 72.11,
  }),
  L({
    id: 'dmf',
    name: 'DMF',
    nameEn: 'Dimethylformamide',
    category: 'alcohol_solvent',
    density: 944,
    viscosity: 9.2e-4,
    vaporPressure: 400,
    molarMass: 73.09,
  }),

  // —— 酸 / 碱 / 溶液 ——
  L({
    id: 'h2so4_98',
    name: '硫酸 98%',
    nameEn: 'Sulfuric acid 98%',
    category: 'acid_alkali',
    density: 1840,
    viscosity: 0.025,
    vaporPressure: 1,
  }),
  L({
    id: 'h2so4_50',
    name: '硫酸 50%',
    nameEn: 'Sulfuric acid 50%',
    category: 'acid_alkali',
    density: 1400,
    viscosity: 0.006,
    vaporPressure: 500,
  }),
  L({
    id: 'hcl_37',
    name: '盐酸 37%',
    nameEn: 'Hydrochloric acid 37%',
    category: 'acid_alkali',
    density: 1180,
    viscosity: 0.0019,
    vaporPressure: 1.5e4,
  }),
  L({
    id: 'hno3_70',
    name: '硝酸 70%',
    nameEn: 'Nitric acid 70%',
    category: 'acid_alkali',
    density: 1410,
    viscosity: 0.0015,
    vaporPressure: 800,
  }),
  L({
    id: 'naoh_50',
    name: '氢氧化钠溶液 50%',
    nameEn: 'NaOH 50%',
    category: 'acid_alkali',
    density: 1525,
    viscosity: 0.08,
    vaporPressure: 200,
  }),
  L({
    id: 'naoh_20',
    name: '氢氧化钠溶液 20%',
    nameEn: 'NaOH 20%',
    category: 'acid_alkali',
    density: 1220,
    viscosity: 0.004,
    vaporPressure: 1500,
  }),
  L({
    id: 'nh3_water_25',
    name: '氨水 25%',
    nameEn: 'Aqueous ammonia 25%',
    category: 'acid_alkali',
    density: 910,
    viscosity: 0.0012,
    vaporPressure: 5e4,
  }),
  L({
    id: 'brine_nacl_20',
    name: '盐水 NaCl 20%wt',
    nameEn: 'Brine NaCl 20%',
    category: 'acid_alkali',
    density: 1148,
    viscosity: 0.0018,
    vaporPressure: 1800,
  }),
  L({
    id: 'caustic_wash',
    name: '碱洗液 (典型)',
    nameEn: 'Caustic wash typical',
    category: 'acid_alkali',
    density: 1100,
    viscosity: 0.002,
    vaporPressure: 2000,
  }),

  // —— 制冷剂 ——
  G({
    id: 'r134a_gas',
    name: 'R134a (气, 参考)',
    nameEn: 'R134a vapor',
    category: 'refrigerant',
    density: 4.25,
    viscosity: 1.2e-5,
    kappa: 1.12,
    molarMass: 102.03,
    cas: '811-97-2',
    note: '近饱和蒸气参考；请按工况 P/T 修正',
  }),
  L({
    id: 'r134a_liquid',
    name: 'R134a (液, 参考)',
    nameEn: 'R134a liquid',
    category: 'refrigerant',
    density: 1225,
    viscosity: 2.1e-4,
    vaporPressure: 5.7e5,
    molarMass: 102.03,
  }),
  G({
    id: 'r22_gas',
    name: 'R22 (气, 参考)',
    nameEn: 'R22 vapor',
    category: 'refrigerant',
    density: 3.6,
    viscosity: 1.2e-5,
    kappa: 1.18,
    molarMass: 86.47,
  }),
  L({
    id: 'r22_liquid',
    name: 'R22 (液, 参考)',
    nameEn: 'R22 liquid',
    category: 'refrigerant',
    density: 1210,
    viscosity: 1.9e-4,
    vaporPressure: 9.1e5,
    molarMass: 86.47,
  }),
  G({
    id: 'r410a_gas',
    name: 'R410A (气, 参考)',
    nameEn: 'R410A vapor',
    category: 'refrigerant',
    density: 4.0,
    viscosity: 1.3e-5,
    kappa: 1.14,
    molarMass: 72.6,
  }),
  L({
    id: 'r410a_liquid',
    name: 'R410A (液, 参考)',
    nameEn: 'R410A liquid',
    category: 'refrigerant',
    density: 1080,
    viscosity: 1.5e-4,
    vaporPressure: 1.4e6,
  }),
  G({
    id: 'r1234yf_gas',
    name: 'R1234yf (气, 参考)',
    nameEn: 'R1234yf vapor',
    category: 'refrigerant',
    density: 3.5,
    viscosity: 1.1e-5,
    kappa: 1.1,
    molarMass: 114.04,
    cas: '754-12-1',
  }),
  L({
    id: 'r123_liquid',
    name: 'R123 (液, 参考)',
    nameEn: 'R123 liquid',
    category: 'refrigerant',
    density: 1460,
    viscosity: 4.5e-4,
    vaporPressure: 7.8e4,
    molarMass: 152.93,
  }),
  G({
    id: 'ammonia_ref_gas',
    name: '氨制冷剂 (气)',
    nameEn: 'Ammonia refrigerant vapor',
    category: 'refrigerant',
    density: 0.73,
    viscosity: 9.5e-6,
    kappa: 1.31,
    molarMass: 17.03,
  }),
  L({
    id: 'ammonia_ref_liquid',
    name: '氨制冷剂 (液)',
    nameEn: 'Ammonia refrigerant liquid',
    category: 'refrigerant',
    density: 610,
    viscosity: 1.4e-4,
    vaporPressure: 8.6e5,
    molarMass: 17.03,
  }),

  // —— 导热油 ——
  L({
    id: 'thermal_oil_200c',
    name: '导热油 (约 200°C)',
    nameEn: 'Thermal oil ~200°C',
    category: 'thermal_oil',
    density: 850,
    viscosity: 0.002,
    vaporPressure: 100,
    note: '矿物/合成导热油典型范围，以厂家曲线为准',
    tags: ['CONVAL热油类'],
  }),
  L({
    id: 'thermal_oil_300c',
    name: '导热油 (约 300°C)',
    nameEn: 'Thermal oil ~300°C',
    category: 'thermal_oil',
    density: 780,
    viscosity: 6e-4,
    vaporPressure: 500,
  }),
  L({
    id: 'dowtherm_like',
    name: '联苯类导热油 (参考)',
    nameEn: 'Biphenyl-type thermal fluid',
    category: 'thermal_oil',
    density: 1060,
    viscosity: 0.004,
    vaporPressure: 50,
  }),
  L({
    id: 'silicone_oil',
    name: '硅油 (参考)',
    nameEn: 'Silicone oil',
    category: 'thermal_oil',
    density: 960,
    viscosity: 0.05,
    vaporPressure: 1,
  }),

  // —— 浆料 / 高粘（PRESO 楔形等） ——
  L({
    id: 'pulp_low',
    name: '纸浆 (低浓 ~2%)',
    nameEn: 'Pulp slurry low consistency',
    category: 'slurry_viscous',
    density: 1010,
    viscosity: 0.02,
    vaporPressure: 2300,
    note: '非牛顿，粘度为表观值',
    tags: ['CONVAL纸浆'],
  }),
  L({
    id: 'pulp_med',
    name: '纸浆 (中浓 ~8%)',
    nameEn: 'Pulp slurry medium',
    category: 'slurry_viscous',
    density: 1030,
    viscosity: 0.2,
    vaporPressure: 2300,
    tags: ['CONVAL纸浆'],
  }),
  L({
    id: 'coal_water_slurry',
    name: '水煤浆',
    nameEn: 'Coal-water slurry',
    category: 'slurry_viscous',
    density: 1200,
    viscosity: 0.3,
    vaporPressure: 2000,
    tags: ['PRESO COIN'],
  }),
  L({
    id: 'lime_slurry',
    name: '石灰浆',
    nameEn: 'Lime slurry',
    category: 'slurry_viscous',
    density: 1150,
    viscosity: 0.05,
    vaporPressure: 2200,
  }),
  L({
    id: 'mud_drilling',
    name: '钻井泥浆 (参考)',
    nameEn: 'Drilling mud',
    category: 'slurry_viscous',
    density: 1200,
    viscosity: 0.04,
    vaporPressure: 2000,
  }),
  L({
    id: 'asphalt_emulsion',
    name: '沥青乳液',
    nameEn: 'Asphalt emulsion',
    category: 'slurry_viscous',
    density: 1000,
    viscosity: 0.1,
    vaporPressure: 2000,
  }),

  // —— 低温介质 ——
  L({
    id: 'lng_liquid',
    name: 'LNG (液, 约 -162°C)',
    nameEn: 'LNG liquid',
    category: 'cryogenic',
    density: 450,
    viscosity: 1.2e-4,
    vaporPressure: 1.1e5,
    molarMass: 16.5,
  }),
  G({
    id: 'lng_boiloff',
    name: 'LNG 蒸发气 BOG',
    nameEn: 'LNG boil-off gas',
    category: 'cryogenic',
    density: 0.7,
    viscosity: 1.0e-5,
    kappa: 1.3,
    molarMass: 17,
  }),
  L({
    id: 'ln2',
    name: '液氮 (-196°C)',
    nameEn: 'Liquid nitrogen',
    category: 'cryogenic',
    density: 808,
    viscosity: 1.6e-4,
    vaporPressure: 1.01e5,
    molarMass: 28.01,
  }),
  L({
    id: 'lox',
    name: '液氧 (-183°C)',
    nameEn: 'Liquid oxygen',
    category: 'cryogenic',
    density: 1141,
    viscosity: 1.9e-4,
    vaporPressure: 1.01e5,
    molarMass: 32.0,
  }),
  L({
    id: 'lco2',
    name: '液态 CO₂ (加压)',
    nameEn: 'Liquid CO2',
    category: 'cryogenic',
    density: 900,
    viscosity: 8e-5,
    vaporPressure: 5.7e6,
    molarMass: 44.01,
    note: '需高于三相点压力',
  }),

  // —— 其他 ——
  L({
    id: 'milk',
    name: '牛奶 (参考)',
    nameEn: 'Milk',
    category: 'other',
    density: 1030,
    viscosity: 0.002,
    vaporPressure: 2300,
  }),
  L({
    id: 'vegetable_oil',
    name: '植物油 (参考)',
    nameEn: 'Vegetable oil',
    category: 'other',
    density: 920,
    viscosity: 0.06,
    vaporPressure: 1,
  }),
  L({
    id: 'hydraulic_oil',
    name: '液压油 ISO VG46',
    nameEn: 'Hydraulic oil VG46',
    category: 'other',
    density: 875,
    viscosity: 0.04,
    vaporPressure: 10,
  }),
]

export function getFluid(id: string): FluidProps {
  const f = FLUIDS.find((x) => x.id === id)
  if (!f) throw new Error(`未知工质: ${id}`)
  return f
}

export function fluidsByCategory(): { category: FluidCategory; label: string; items: FluidProps[] }[] {
  const order = Object.keys(CATEGORY_LABEL) as FluidCategory[]
  return order
    .map((category) => ({
      category,
      label: CATEGORY_LABEL[category],
      items: FLUIDS.filter((f) => f.category === category),
    }))
    .filter((g) => g.items.length > 0)
}

export function searchFluids(query: string): FluidProps[] {
  const q = query.trim().toLowerCase()
  if (!q) return FLUIDS
  return FLUIDS.filter((f) => {
    const hay = [
      f.id,
      f.name,
      f.nameEn,
      f.cas ?? '',
      ...(f.tags ?? []),
      CATEGORY_LABEL[f.category],
    ]
      .join(' ')
      .toLowerCase()
    return hay.includes(q)
  })
}

/** 理想气体密度修正 ρ = ρ_ref * (P/P_ref) * (T_ref/T) */
export function gasDensity(
  refDensity: number,
  pPa: number,
  tK: number,
  pRef = 101325,
  tRef = 293.15,
): number {
  return refDensity * (pPa / pRef) * (tRef / tK)
}

export const FLUID_COUNT = FLUIDS.length
